config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :flashvendors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flashvendor.rb
class Flashvendor < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flashvendors_controller.rb
class FlashvendorsController < ApplicationController
  before_action :set_flashvendor, only: [:show, :edit, :update, :destroy]

  # GET /flashvendors
  # GET /flashvendors.json
  def index
    @flashvendors = Flashvendor.all
  end

  # GET /flashvendors/1
  # GET /flashvendors/1.json
  def show
  end

  # GET /flashvendors/new
  def new
    @flashvendor = Flashvendor.new
  end

  # GET /flashvendors/1/edit
  def edit
  end

  # POST /flashvendors
  # POST /flashvendors.json
  def create
    @flashvendor = Flashvendor.new(flashvendor_params)

    respond_to do |format|
      if @flashvendor.save
        format.html { redirect_to @flashvendor, notice: 'Flashvendor was successfully created.' }
        format.json { render :show, status: :created, location: @flashvendor }
      else
        format.html { render :new }
        format.json { render json: @flashvendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flashvendors/1
  # PATCH/PUT /flashvendors/1.json
  def update
    respond_to do |format|
      if @flashvendor.update(flashvendor_params)
        format.html { redirect_to @flashvendor, notice: 'Flashvendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @flashvendor }
      else
        format.html { render :edit }
        format.json { render json: @flashvendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flashvendors/1
  # DELETE /flashvendors/1.json
  def destroy
    @flashvendor.destroy
    respond_to do |format|
      format.html { redirect_to flashvendors_url, notice: 'Flashvendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flashvendor
      @flashvendor = Flashvendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flashvendor_params
      params.require(:flashvendor).permit(:vendor_name, :vendor_description, :vendor_url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashvendors_helper.rb
module FlashvendorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flashvendors/_form.html.erb
<%= form_for(flashvendor) do |f| %>
  <% if flashvendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flashvendor.errors.count, "error") %> prohibited this flashvendor from being saved:</h2>

      <ul>
      <% flashvendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vendor_name %>
    <%= f.text_field :vendor_name %>
  </div>

  <div class="field">
    <%= f.label :vendor_description %>
    <%= f.text_area :vendor_description %>
  </div>

  <div class="field">
    <%= f.label :vendor_url %>
    <%= f.text_field :vendor_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flashvendors/edit.html.erb
<h1>Editing Flashvendor</h1>

<%= render 'form', flashvendor: @flashvendor %>

<%= link_to 'Show', @flashvendor %> |
<%= link_to 'Back', flashvendors_path %>

app/views/flashvendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flashvendors</h1>

<table>
  <thead>
    <tr>
      <th>Vendor name</th>
      <th>Vendor description</th>
      <th>Vendor url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flashvendors.each do |flashvendor| %>
      <tr>
        <td><%= flashvendor.vendor_name %></td>
        <td><%= flashvendor.vendor_description %></td>
        <td><%= flashvendor.vendor_url %></td>
        <td><%= link_to 'Show', flashvendor %></td>
        <td><%= link_to 'Edit', edit_flashvendor_path(flashvendor) %></td>
        <td><%= link_to 'Destroy', flashvendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flashvendor', new_flashvendor_path %>

app/views/flashvendors/new.html.erb
<h1>New Flashvendor</h1>

<%= render 'form', flashvendor: @flashvendor %>

<%= link_to 'Back', flashvendors_path %>

app/views/flashvendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vendor name:</strong>
  <%= @flashvendor.vendor_name %>
</p>

<p>
  <strong>Vendor description:</strong>
  <%= @flashvendor.vendor_description %>
</p>

<p>
  <strong>Vendor url:</strong>
  <%= @flashvendor.vendor_url %>
</p>

<%= link_to 'Edit', edit_flashvendor_path(@flashvendor) %> |
<%= link_to 'Back', flashvendors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>